# Generated by Django 4.2.9 on 2024-01-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_nagranie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cwiczenie',
            old_name='opis',
            new_name='link',
        ),
    ]
