# Generated by Django 4.2.9 on 2024-01-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_opis_cwiczenie_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numeracja', models.PositiveIntegerField()),
            ],
        ),
    ]
