# Generated by Django 4.2.9 on 2024-01-07 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_serie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nagranie',
        ),
    ]
