# Generated by Django 4.2.9 on 2024-01-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_nagranie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Powtórzenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numeracja', models.PositiveIntegerField()),
            ],
        ),
    ]
