# Generated by Django 4.2.9 on 2024-01-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_nagranie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ciezar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.DecimalField(decimal_places=1, max_digits=500)),
            ],
        ),
        migrations.CreateModel(
            name='powtorzenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracja_powtorzenia', models.DecimalField(decimal_places=0, max_digits=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Ciężar',
        ),
        migrations.DeleteModel(
            name='Powtórzenia',
        ),
        migrations.RenameField(
            model_name='komentarz',
            old_name='Kom',
            new_name='kom',
        ),
        migrations.RenameField(
            model_name='tempo',
            old_name='XXXX',
            new_name='xxxx',
        ),
        migrations.RemoveField(
            model_name='lp',
            name='numerek',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='Numeracja',
        ),
        migrations.AddField(
            model_name='lp',
            name='numeracja_lp',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='numeracja_serie',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=100),
            preserve_default=False,
        ),
    ]
