# Generated by Django 4.2.9 on 2024-01-16 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_seria_delete_ciezar_delete_komentarz_delete_lp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seria',
            name='podopieczny',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cwiczenie',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seria',
            name='uwagi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
